// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0nGPhG7X0R_KToSv7rS7YXRA_9ZH7OWI',
    appId: '1:363373528048:web:d2a2839f38bb0e00355335',
    messagingSenderId: '363373528048',
    projectId: 'chat-2697f',
    authDomain: 'chat-2697f.firebaseapp.com',
    storageBucket: 'chat-2697f.appspot.com',
    measurementId: 'G-33TPJP0CE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4xn1DAxjjVN9WeOPFqWZ4SInKLzta7Yw',
    appId: '1:363373528048:android:93045e98c315154d355335',
    messagingSenderId: '363373528048',
    projectId: 'chat-2697f',
    storageBucket: 'chat-2697f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPreogKsCoZ7jXAIbiN9kObURJ38tCsp8',
    appId: '1:363373528048:ios:9f054f41fe67f429355335',
    messagingSenderId: '363373528048',
    projectId: 'chat-2697f',
    storageBucket: 'chat-2697f.appspot.com',
    iosClientId: '363373528048-vb8eubj3jragf1jh0gveebjeitmckmvl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatboxApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPreogKsCoZ7jXAIbiN9kObURJ38tCsp8',
    appId: '1:363373528048:ios:9f054f41fe67f429355335',
    messagingSenderId: '363373528048',
    projectId: 'chat-2697f',
    storageBucket: 'chat-2697f.appspot.com',
    iosClientId: '363373528048-vb8eubj3jragf1jh0gveebjeitmckmvl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatboxApp',
  );
}
